<a href="https://colab.research.google.com/github/meriemdouider1/pfe/blob/main/featureselection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
import sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import roc_auc_score, r2_score

from mlxtend.feature_selection import SequentialFeatureSelector as SFS
import sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
import numpy 
import sklearn.metrics as metrics
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import LeaveOneOut
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import make_scorer
import matplotlib.pyplot as plt
from sklearn.model_selection import LeaveOneOut
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
from sklearn import datasets, metrics, model_selection, svm
import numpy as np
import matplotlib.pyplot as plt

from sklearn import svm, datasets
from sklearn.metrics import auc
from sklearn.metrics import plot_roc_curve
from sklearn.model_selection import StratifiedKFold

In [78]:
import matplotlib.pyplot as plt
from sklearn.model_selection import LeaveOneOut
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
from sklearn import datasets, metrics, model_selection, svm
from sklearn.metrics import matthews_corrcoef
from sklearn.svm import SVC

In [79]:
Cl = '/content/cs-longiaN+.xlsx'
data= pd.read_excel(Cl,
sheet_name=0,
header=0,
index_col=False,
keep_default_na=True)

In [80]:
del data["Source"]
del data["CodeSite"]

In [81]:
data

        X_long      Y_lat  Cs_longia  ...  Vent_Oct  Vent_Nov  Vent_Dec
0   -15.911420  23.794740          1  ...       5.4       5.5       4.9
1   -13.188370  27.132950          1  ...       4.3       3.7       3.8
2   -13.188370  27.132950          1  ...       4.3       3.7       3.8
3   -13.185620  27.157940          0  ...       4.1       3.7       3.9
4   -13.167180  27.157730          0  ...       4.2       3.6       3.8
..         ...        ...        ...  ...       ...       ...       ...
249  -5.366667  35.766667          1  ...       4.0       4.0       4.2
250  -5.816667  35.783333          1  ...       3.6       3.8       4.0
251  -5.366667  35.833333          1  ...       4.0       3.9       4.3
252  -5.558611  35.841944          1  ...       3.6       3.4       3.6
253  -5.483333  35.900000          1  ...       4.0       4.0       4.2

[254 rows x 226 columns]

In [82]:
X1 = data.loc[:, data.columns != 'Cs_longia']
y1 = data.Cs_longia

In [89]:
# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
X1,y1,test_size=0.20)

In [90]:
X_train

        X_long      Y_lat     Bovins  ...  Vent_Oct  Vent_Nov  Vent_Dec
189  -9.216667  30.400000   0.000000  ...       2.4       2.5       2.5
222  -6.683062  34.046605  10.472515  ...       3.0       2.9       3.0
78   -6.772463  34.005190   0.000000  ...       3.1       3.0       3.0
92   -6.791708  33.878230   5.773937  ...       3.3       2.9       2.9
244  -5.269722  35.171389   4.332951  ...       3.2       3.0       3.0
..         ...        ...        ...  ...       ...       ...       ...
86   -7.384917  33.605960  27.173939  ...       3.1       3.0       3.1
135  -4.750000  34.503000   6.528858  ...       2.4       2.4       2.1
195  -7.685324  32.069867   3.819696  ...       2.4       2.3       2.4
142  -5.350000  35.569000   0.000000  ...       3.7       3.6       3.7
5   -13.201560  27.165070   0.000000  ...       4.6       3.8       3.9

[203 rows x 225 columns]

In [91]:
y_train

189    1
222    1
78     0
92     0
244    1
      ..
86     0
135    0
195    1
142    0
5      0
Name: Cs_longia, Length: 203, dtype: int64

In [92]:
print('Training dataset shape:', X_train.shape, y_train.shape)
print('Testing dataset shape:', X_test.shape, y_test.shape)

Training dataset shape: (203, 225) (203,)
Testing dataset shape: (51, 225) (51,)

In [93]:
from mlxtend.feature_selection import SequentialFeatureSelector as sfs
# Build RF classifier to use in feature selection
clf = XGBClassifier(scale_pos_weight=1.5,learning_rate=0.1,max_depth=5,n_estimators=100)

# Build step forward feature selection
sfsT = sfs(clf,
           k_features=20,
           forward=True,
           floating=False,
           verbose=2,
           scoring='roc_auc',
           cv=5)

# Perform SFFS
sfsT = sfsT.fit(X_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 225 out of 225 | elapsed:   18.7s finished

[2021-08-13 13:56:27] Features: 1/20 -- score: 0.6999448621553885[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 224 out of 224 | elapsed:   21.9s finished

[2021-08-13 13:56:49] Features: 2/20 -- score: 0.7362769423558897[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 223 out of 223 | elapsed:   24.8s finished

[2021-08-13 13:57:14] Features: 3/20 -- score: 0.7447080200501255[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 222 out of 222 | elapsed:   27.3s finished

[2021-08-13 13:57:41] Features: 4/20 -- score: 0.7528408521303258[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 221 out of 221 | elapsed:   28.4s finished

[2021-08-13 13:58:10] Features: 5/20 -- score: 0.7669661654135338[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 220 out of 220 | elapsed:   30.3s finished

[2021-08-13 13:58:40] Features: 6/20 -- score: 0.7841854636591479[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 219 out of 219 | elapsed:   32.1s finished

[2021-08-13 13:59:12] Features: 7/20 -- score: 0.793984962406015[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 218 out of 218 | elapsed:   34.0s finished

[2021-08-13 13:59:46] Features: 8/20 -- score: 0.8066766917293233[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 217 out of 217 | elapsed:   36.0s finished

[2021-08-13 14:00:22] Features: 9/20 -- score: 0.8107957393483709[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 216 out of 216 | elapsed:   37.7s finished

[2021-08-13 14:01:00] Features: 10/20 -- score: 0.8130338345864662[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 215 out of 215 | elapsed:   38.9s finished

[2021-08-13 14:01:39] Features: 11/20 -- score: 0.814938596491228[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 214 out of 214 | elapsed:   40.6s finished

[2021-08-13 14:02:19] Features: 12/20 -- score: 0.814938596491228[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 213 out of 213 | elapsed:   41.1s finished

[2021-08-13 14:03:00] Features: 13/20 -- score: 0.814938596491228[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 212 out of 212 | elapsed:   41.8s finished

[2021-08-13 14:03:42] Features: 14/20 -- score: 0.814437343358396[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 211 out of 211 | elapsed:   42.3s finished

[2021-08-13 14:04:24] Features: 15/20 -- score: 0.8139398496240601[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 210 out of 210 | elapsed:   42.9s finished

[2021-08-13 14:05:07] Features: 16/20 -- score: 0.8157180451127818[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 209 out of 209 | elapsed:   43.9s finished

[2021-08-13 14:05:51] Features: 17/20 -- score: 0.8143421052631579[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 208 out of 208 | elapsed:   44.8s finished

[2021-08-13 14:06:36] Features: 18/20 -- score: 0.8074974937343358[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 207 out of 207 | elapsed:   45.8s finished

[2021-08-13 14:07:22] Features: 19/20 -- score: 0.8080964912280703[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 206 out of 206 | elapsed:   46.4s finished

[2021-08-13 14:08:08] Features: 20/20 -- score: 0.8128972431077693

In [94]:
feat_cols = list(sfsT.k_feature_idx_)
print(feat_cols)

[7, 9, 10, 16, 23, 24, 41, 43, 45, 51, 52, 66, 98, 139, 154, 160, 161, 178, 189, 190]

In [95]:
data.columns[feat_cols]

Index(['Equides', 'ZoneAride', 'ZonePel', 'VegCul', 'VarT_ann_IRM',
       'VarT_bi_IRM', 'Min_TempJ', 'Ph1_TempJ', 'Ph3_TempJ', 'VarT_ann_TempN',
       'VarT_bi_TempN', 'VarT_bi_NDVI', 'Sol_Carbone_terreFine', 'Bio_Tmax',
       'Prec_Janv', 'Prec_Juill', 'Prec_Aout', 'Tmax_Janv', 'Tmax_Dec',
       'Tmin_Janv'],
      dtype='object')

In [96]:
from mlxtend.feature_selection import SequentialFeatureSelector as sfs
# Build RF classifier to use in feature selection
clf = XGBClassifier(scale_pos_weight=1.5,learning_rate=0.1,max_depth=5,n_estimators=100)

# Build step forward feature selection
sfs2 = sfs(clf,
           k_features=11,
           forward=True,
           floating=False,
           verbose=2,
           scoring='roc_auc',
           cv=5)

# Perform SFFS
sfs2 = sfs2.fit(X_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 225 out of 225 | elapsed:   18.8s finished

[2021-08-13 14:09:17] Features: 1/11 -- score: 0.6999448621553885[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 224 out of 224 | elapsed:   21.9s finished

[2021-08-13 14:09:39] Features: 2/11 -- score: 0.7362769423558897[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 223 out of 223 | elapsed:   25.0s finished

[2021-08-13 14:10:04] Features: 3/11 -- score: 0.7447080200501255[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 222 out of 222 | elapsed:   27.3s finished

[2021-08-13 14:10:31] Features: 4/11 -- score: 0.7528408521303258[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 221 out of 221 | elapsed:   28.1s finished

[2021-08-13 14:11:00] Features: 5/11 -- score: 0.7669661654135338[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 220 out of 220 | elapsed:   30.3s finished

[2021-08-13 14:11:30] Features: 6/11 -- score: 0.7841854636591479[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 219 out of 219 | elapsed:   32.1s finished

[2021-08-13 14:12:02] Features: 7/11 -- score: 0.793984962406015[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 218 out of 218 | elapsed:   34.4s finished

[2021-08-13 14:12:36] Features: 8/11 -- score: 0.8066766917293233[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 217 out of 217 | elapsed:   36.2s finished

[2021-08-13 14:13:13] Features: 9/11 -- score: 0.8107957393483709[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 216 out of 216 | elapsed:   38.3s finished

[2021-08-13 14:13:51] Features: 10/11 -- score: 0.8130338345864662[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 215 out of 215 | elapsed:   39.0s finished

[2021-08-13 14:14:30] Features: 11/11 -- score: 0.814938596491228

In [97]:
feat_cols2 = list(sfs2.k_feature_idx_)
print(feat_cols2)

[41, 43, 45, 66, 98, 139, 154, 160, 178, 189, 190]

In [99]:
feature=data.columns[feat_cols2]

In [100]:
feature

Index(['Min_TempJ', 'Ph1_TempJ', 'Ph3_TempJ', 'VarT_bi_NDVI',
       'Sol_Carbone_terreFine', 'Bio_Tmax', 'Prec_Janv', 'Prec_Juill',
       'Tmax_Janv', 'Tmax_Dec', 'Tmin_Janv'],
      dtype='object')

In [103]:
data[feature]

     Min_TempJ  Ph1_TempJ  Ph3_TempJ  ...  Tmax_Janv   Tmax_Dec  Tmin_Janv
0        14721        672        203  ...       21.5  22.500000       14.5
1        14941        643         88  ...       21.9  22.600000       12.0
2        14941        643         88  ...       21.9  22.600000       12.0
3        14854        636         78  ...       21.9  22.700001       12.3
4        14918        651         92  ...       22.0  22.900000       12.4
..         ...        ...        ...  ...        ...        ...        ...
249      14387        670        325  ...       15.2  16.500000        9.4
250      14350        655        388  ...       14.5  16.100000        9.6
251      14385        669        345  ...       15.3  16.400000        9.4
252          0          0          0  ...       16.6  16.799999        8.5
253      14343        671        302  ...       16.0  16.700001        8.7

[254 rows x 11 columns]

In [104]:
T_train=X_train[feature]

In [105]:
T_train

     Min_TempJ  Ph1_TempJ  Ph3_TempJ  ...  Tmax_Janv   Tmax_Dec  Tmin_Janv
189      14732        641        139  ...  19.400000  20.900000        8.3
222      14446        650        109  ...  17.100000  17.799999        6.2
78       14513        665         97  ...  16.799999  18.299999        7.7
92       14466        669        103  ...  17.000000  17.799999        6.3
244      14344        666        148  ...  14.000000  14.300000        3.4
..         ...        ...        ...  ...        ...        ...        ...
86       14515        670        101  ...  17.100000  18.600000        6.9
135      14466        678        129  ...  17.000000  18.000000        5.5
195      14586        640        107  ...  19.200001  18.299999        2.9
142      14407        653         44  ...  17.200001  17.500000        8.6
5        14862        634         80  ...  22.100000  22.900000       12.2

[203 rows x 11 columns]

In [106]:
T_Test=X_test[feature]

In [107]:
T_Test

     Min_TempJ  Ph1_TempJ  Ph3_TempJ  ...  Tmax_Janv   Tmax_Dec  Tmin_Janv
250      14350        655        388  ...  14.500000  16.100000        9.6
93       14490        653         87  ...  16.799999  17.799999        6.8
83       14464        665        108  ...  16.600000  18.400000        8.0
36       14757        647        119  ...  19.400000  20.900000        8.5
212      14483        678        112  ...  16.799999  17.900000        5.4
79       14461        648         90  ...  17.200001  17.799999        6.2
58       14597        636        152  ...  17.700001  18.400000        4.5
225      14486        662         75  ...  17.299999  18.000000        6.6
148      14470        682        139  ...  17.200001  17.299999        4.8
169      14987        652        124  ...  21.600000  22.700001       11.3
240      14272        648        146  ...  12.200000  11.400000        2.1
101      14566        677        108  ...  17.900000  19.100000        6.0
182      14738        644        140  ...  19.200001  20.799999        9.1
22       14675        643        132  ...  18.000000  19.700001       10.7
125      14344        652        115  ...  16.500000  17.000000        4.9
226      14417        664         85  ...  15.900000  17.500000        7.9
146      14420        671        113  ...  15.900000  17.299999        7.5
76       14507        678        106  ...  17.000000  18.000000        5.8
69       14635        640        137  ...  17.900000  18.100000        3.3
117      14518        676        127  ...  17.200001  17.000000        2.9
7        14862        634         80  ...  22.100000  22.900000       12.2
187      14557        635        125  ...  13.900000  13.700000        1.3
52       14568        649        162  ...  16.100000  17.900000        8.3
196      14580        666        105  ...  17.900000  18.500000        4.5
94       14483        651         93  ...  16.799999  18.000000        7.1
54       14687        654        117  ...  16.900000  18.799999        9.3
85       14490        664        109  ...  17.000000  18.400000        7.1
66       14576        663        107  ...  16.000000  15.200000        1.4
210      14478        672         76  ...  16.900000  18.700001        8.3
72       14452        652        129  ...  17.299999  17.200001        3.8
114      14208        659        318  ...  10.500000  10.200000       -2.4
47       14651        658         87  ...  19.400000  21.200001       11.8
49       14857        639        127  ...  20.100000  21.700001        9.7
112      14173        654        309  ...   9.800000   9.600000       -2.9
34       14750        637        128  ...  18.700001  20.600000       10.1
68       14647        639        144  ...  18.100000  18.400000        3.7
64       14549        653        136  ...  16.799999  16.799999        3.1
154      14690        630        122  ...  18.799999  18.799999        4.2
253      14343        671        302  ...  16.000000  16.700001        8.7
230      14409        678        150  ...  15.700000  15.700000        4.1
143          0          0          0  ...  16.600000  17.000000        9.3
98       14511        683        101  ...  17.400000  18.500000        5.9
243      14290        669         25  ...  12.800000  13.300000        2.7
202      14236        644        384  ...   8.700000   8.100000       -3.9
97       14463        653         77  ...  16.500000  18.000000        7.4
174      14687        654        117  ...  17.200001  18.200001        7.1
77       14474        672        108  ...  17.100000  18.000000        5.8
81       14505        665         95  ...  16.799999  17.900000        7.2
44       14615        653        153  ...  16.700001  17.000000        3.7
116      14437        664        119  ...  16.400000  15.800000        2.1
170      14828        650        130  ...  20.700001  22.000000        9.9

[51 rows x 11 columns]

In [110]:
from sklearn.metrics import accuracy_score as acc
# Build full model with selected features
clf = XGBClassifier(scale_pos_weight=1.5,learning_rate=0.1,max_depth=5,n_estimators=100)
clf.fit(T_train, y_train)

y_train_pred = clf.predict(T_train)
print('Training accuracy on selected features: %.3f' % acc(y_train, y_train_pred))

y_test_pred = clf.predict(T_Test)
print('Testing accuracy on selected features: %.3f' % acc(y_test, y_test_pred))

Training accuracy on selected features: 0.975
Testing accuracy on selected features: 0.667

In [111]:
from sklearn.metrics import matthews_corrcoef
def tp1(y_true, y_pred): 
    MCC= matthews_corrcoef(y_true, y_pred)
    return MCC

In [113]:
tp1(y_test,y_test_pred)

0.33694334391567654

In [114]:
tp1(y_train,y_train_pred)

0.9510897178860445

--------------------------------------------------------

-----------------------------------------

In [ ]:
---------

In [122]:
lst = ["Coniferes",'ZonePel', 'Lesfeuillus','VegInond', 'Amp2_IRM', 'VarT_tri_IRM','Amp1_TempJ', 'VarT_ann_NDVI', 'Bio_Pre_sec', 'Rad_Dec', 'Tmax_Mars', 'Tmax_Avril', 'Vap_Sept', 'Vent_Mars', 'Vent_Juin']

In [123]:
lst

['Coniferes',
 'ZonePel',
 'Lesfeuillus',
 'VegInond',
 'Amp2_IRM',
 'VarT_tri_IRM',
 'Amp1_TempJ',
 'VarT_ann_NDVI',
 'Bio_Pre_sec',
 'Rad_Dec',
 'Tmax_Mars',
 'Tmax_Avril',
 'Vap_Sept',
 'Vent_Mars',
 'Vent_Juin']

In [124]:
T_train1=X_train[lst]
T_Test1=X_test[lst]

In [125]:
from sklearn.metrics import accuracy_score as acc
# Build full model with selected features
clf = XGBClassifier(scale_pos_weight=1.5,learning_rate=0.1,max_depth=5,n_estimators=100)
clf.fit(T_train1, y_train)

y_train_pred = clf.predict(T_train1)
print('Training accuracy on selected features: %.3f' % acc(y_train, y_train_pred))

y_test_pred = clf.predict(T_Test1)
print('Testing accuracy on selected features: %.3f' % acc(y_test, y_test_pred))

tp1(y_test,y_test_pred)

Training accuracy on selected features: 0.970
Testing accuracy on selected features: 0.784

0.5734219293243853

In [126]:
from sklearn.metrics import accuracy_score as acc
# Build full model with selected features
clf1 = XGBClassifier(scale_pos_weight=1.5,learning_rate=0.1,max_depth=5,n_estimators=100)
clf1.fit(T_train1, y_train)

y_train_pred = clf1.predict(T_train1)
print('Training accuracy on selected features: %.3f' % acc(y_train, y_train_pred))

y_test_pred = clf1.predict(T_Test1)
print('Testing accuracy on selected features: %.3f' % acc(y_test, y_test_pred))

tp1(y_test,y_test_pred)

Training accuracy on selected features: 0.970
Testing accuracy on selected features: 0.784

0.5734219293243853